### ISSUE TITLE
Unhandled exception on polizei

### ISSUE THREAD

**Issue by GodOfOwls** [mojurasu/kantek#1]
Traceback (most recent call last):
      File "C:\Program Files (x86)\Python37-32\lib\site-packages\telethon\client\updates.py", line 335, in _dispatch_update
       await callback(event)
      File "G:\JonasStuff\Desktop\kantek\kantek\plugins\autobahn\polizei.py", line 37, in polizei
        ban_type, ban_reason = await _check_message(event)
      File "G:\JonasStuff\Desktop\kantek\kantek\plugins\autobahn\polizei.py", line 87, in _check_message
        if msg.from_id < 610000000:
    TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by SitiSchu** [comment]
Tracked internally as #KV2-96

**Comment by SitiSchu** [comment]
Fixed with fa524502ddf3e3fffd3bf68c4e2b7fe3e73adc63, forgot about the issue tho
